In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('F:/Natural_Language_porcessing/train.csv')

In [5]:
data.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [8]:
# We are dropping the nan values in the dataset using the dropna

In [6]:
data = data.dropna()

In [7]:
data.shape

(18285, 5)

In [9]:
# Spliting the data into independent and dependent dataset

In [10]:
x = data.drop(columns='label')
y = data['label']

In [11]:
x.shape

(18285, 4)

In [13]:
## Importing the lbraries
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [14]:
from tensorflow.keras.layers import Dense,LSTM

In [26]:
voc_size = 5000

In [16]:
x_copy  = x.copy().

In [20]:
x_copy.reset_index(inplace = True)

In [23]:
x_copy.head(10) # now the index is correct

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   
5      5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6      7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7      9   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8     10  10  Obama’s Organizing for Action Partners with So...   
9     11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6               Alissa J. Rubin   
7  Megan Twohey and Scott Shane   
8                   Aaron Klein   
9               Chris Tomlinson   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...  
5  In these trying times, Jackie Mason is the Voi...  
6  PARIS  —   France chose an idealistic, traditi...  
7  A week before Michael T. Flynn resigned as nat...  
8  Organizing for Action, the activist group that...  
9  The BBC produced spoof on the “Real Housewives...

In [24]:
## Data preprocessing 

In [25]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer,PorterStemmer

In [27]:
lemmat = WordNetLemmatizer()

In [30]:
item = []
for i in range(0,len(x_copy)):
    review = re.sub('[^A-Za-z]',' ',x_copy['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmat.lemmatize(word)for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    item.append(review)

In [32]:
item

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'beno hamon win french socialist party presidential nomination new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll social medium blog forum website',
 'major league soccer argentine find home success new york time',
 'well fargo chief abruptly step new york time',
 'anonymous donor pay 

In [31]:
## now we got the text data and we have to make this text data into a one_hot format

In [34]:
one_hot_code = [one_hot(word,voc_size) for word in item]

In [35]:
one_hot_code

[[4930, 2160, 3258, 2040, 1620, 182, 3757, 335, 3351, 4178],
 [4585, 1628, 694, 594, 4099, 2192, 657],
 [4767, 1359, 3074, 2818],
 [3068, 2169, 492, 487, 2613, 2046],
 [4018, 4099, 2923, 41, 1295, 4420, 4099, 1105, 2815, 4618],
 [2026,
  3027,
  4625,
  1719,
  1630,
  3619,
  918,
  4051,
  3403,
  3317,
  686,
  3190,
  231,
  2936,
  657],
 [2762, 4931, 3480, 3720, 3897, 143, 3696, 1850, 4555, 4895, 363],
 [4474, 3838, 4043, 2631, 611, 1523, 3619, 4615, 4555, 4895, 363],
 [1410, 3330, 39, 159, 2879, 3585, 1779, 2526, 3619, 777],
 [1773, 4667, 2983, 3357, 2490, 905, 3674, 1201],
 [3501, 2675, 4361, 4183, 3702, 1097, 4272, 4671, 1602, 872, 4907],
 [487, 4298, 1620, 3211, 3619, 611],
 [883, 4994, 3976, 3122, 3366, 336, 4429, 488, 1274],
 [2246, 2858, 4192, 4339, 3428, 3589, 1646, 4555, 4895, 363],
 [1705, 3225, 3330, 1685, 4396, 4555, 4895, 363],
 [439, 4345, 3218, 1422, 1713, 1560, 1516, 1895, 4125, 3591],
 [3733, 4643, 1628],
 [932, 4078, 3802, 1716, 3619, 4270, 4104, 657],
 [2645, 4

In [42]:
# highest lenght of string from the list
length = max(item,key = len)
print('The length Size:' ,length)

The length Size: roger stone update stop steal exit poll program globalist establishment creating false expectation close race using fake poll rigging voting machine meet expectation nationalistic constitutional free market awakening rothschild soros hillary chance stealing u election shrinking day whole system rigged exposed american people fed elitist deviant panicking


In [ ]:
## We are doing making the padding in each sentences

In [44]:
sentence_len = 46
embedded_doc = pad_sequences(one_hot_code,maxlen=sentence_len,padding='pre')
print(embedded_doc)

[[   0    0    0 ...  335 3351 4178]
 [   0    0    0 ... 4099 2192  657]
 [   0    0    0 ... 1359 3074 2818]
 ...
 [   0    0    0 ... 4555 4895  363]
 [   0    0    0 ... 2644 4354 4617]
 [   0    0    0 ... 2669 2318 3976]]


In [45]:
embedded_doc[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0, 4930, 2160, 3258, 2040, 1620,  182, 3757,  335,
       3351, 4178])

In [46]:
vector_features = 45

In [47]:
# creating the model
model = Sequential()
model.add(Embedding(voc_size,vector_features,input_length = sentence_len))
model.add(LSTM(100))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [48]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 46, 45)            225000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               58400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 283,501
Trainable params: 283,501
Non-trainable params: 0
_________________________________________________________________


In [49]:
x.shape,y.shape

((18285, 4), (18285,))

In [50]:
len(embedded_doc),y.shape

(18285, (18285,))

In [51]:
## chaning this into an array
x_final = np.array(embedded_doc)
y_final = np.array(y)

In [53]:
x_final.shape,y_final.shape

((18285, 46), (18285,))

In [54]:
### Training the model
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_final,y_final,test_size = 0.33,random_state = 0)

In [56]:
## model trainig
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Train on 12250 samples, validate on 6035 samples
Epoch 1/10
12250/12250 [==============================] - 21s 2ms/sample - loss: 0.0141 - acc: 0.9950 - val_loss: 0.5212 - val_acc: 0.9070
Epoch 2/10
12250/12250 [==============================] - 21s 2ms/sample - loss: 0.0078 - acc: 0.9971 - val_loss: 0.6646 - val_acc: 0.9014
Epoch 3/10
12250/12250 [==============================] - 21s 2ms/sample - loss: 0.0047 - acc: 0.9986 - val_loss: 0.5297 - val_acc: 0.9115
Epoch 4/10
12250/12250 [==============================] - 21s 2ms/sample - loss: 0.0051 - acc: 0.9990 - val_loss: 0.5639 - val_acc: 0.9059
Epoch 5/10
12250/12250 [==============================] - 20s 2ms/sample - loss: 0.0011 - acc: 0.9999 - val_loss: 0.6807 - val_acc: 0.9021
Epoch 6/10
12250/12250 [==============================] - 20s 2ms/sample - loss: 2.1959e-04 - acc: 1.0000 - val_loss: 0.7220 - val_acc: 0.9026
Epoch 7/10
12250/12250 [==============================] - 20s 2ms/sample - loss: 1.1958e-04 - acc: 1.0000 - val_l

In [57]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [58]:
y_pred = model.predict_classes(x_test)

In [59]:
confusion_matrix(y_test,y_pred)

array([[3097,  292],
       [ 304, 2342]], dtype=int64)

In [60]:
accuracy_score(y_test,y_pred)

0.9012427506213753

In [62]:
### Adding the dropout layer for avoid the overfitting problem

In [63]:
from tensorflow.keras.layers import Dropout

In [64]:
embedding_vectors = 45
model = Sequential()
model.add(Embedding(voc_size,embedding_vectors,input_length = sentence_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [65]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 46, 45)            225000    
_________________________________________________________________
dropout (Dropout)            (None, 46, 45)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               58400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 283,501
Trainable params: 283,501
Non-trainable params: 0
_________________________________________________________________


In [66]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Train on 12250 samples, validate on 6035 samples
Epoch 1/10
12250/12250 [==============================] - 25s 2ms/sample - loss: 0.3419 - acc: 0.8348 - val_loss: 0.1989 - val_acc: 0.9162
Epoch 2/10
12250/12250 [==============================] - 22s 2ms/sample - loss: 0.1503 - acc: 0.9386 - val_loss: 0.1975 - val_acc: 0.9180
Epoch 3/10
12250/12250 [==============================] - 22s 2ms/sample - loss: 0.1054 - acc: 0.9603 - val_loss: 0.2233 - val_acc: 0.9137
Epoch 4/10
12250/12250 [==============================] - 21s 2ms/sample - loss: 0.0737 - acc: 0.9737 - val_loss: 0.2452 - val_acc: 0.9138
Epoch 5/10
12250/12250 [==============================] - 21s 2ms/sample - loss: 0.0541 - acc: 0.9820 - val_loss: 0.3228 - val_acc: 0.9067
Epoch 6/10
12250/12250 [==============================] - 20s 2ms/sample - loss: 0.0384 - acc: 0.9883 - val_loss: 0.3327 - val_acc: 0.9120
Epoch 7/10
12250/12250 [==============================] - 20s 2ms/sample - loss: 0.0298 - acc: 0.9905 - val_loss: 0.3

In [67]:
y_prd = model.predict_classes(x_test)

In [68]:
accuracy_score(y_test,y_prd)

0.9121789560894781

In [69]:
confusion_matrix(y_test,y_prd)

array([[3029,  360],
       [ 170, 2476]], dtype=int64)